projects:
  app:
    schemaPath:
      - src/server/schema.graphql
      - src/client/graphql/schema.graphql
    includes: ["src/client/graphql/**/*.graphql"]
    extensions:
      endpoints:
        default: http://localhost:3000/graphql
