schema:
  - "http://localhost:3333/graphql"
  - "./src/client/graphql/schema.graphql"
schemaEntrypoints: "./src/client/schema.graphqls"
documents:
  - "**/*.graphql"
  - "!**/schema.graphql"
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
config:
  reactApolloVersion: 3
  preResolveTypes: true
  dedupeOperationSuffix: true
  nonOptionalTypename: true
cacheDir: __generated__
