schema:
  - "http://localhost:3333/graphql"
  - "./src/client/graphql/schema.graphql"
documents:
  - "**/*.graphql"
  - "!**/schema.graphql"
  - "!**/*-values.graphql"
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
config:
  reactApolloVersion: 3
  preResolveTypes: true
  dedupeOperationSuffix: true
  useTypeImports: true
  immutableTypes: true
  pureMagicComment: true
cacheDir: __generated__
