projects:
  app:
    schemaPath:
      - http://localhost:3333/graphql
      - src/client/graphql/schema.graphql
    includes: ["src/client/graphql/**/*.graphql"]
    extensions:
      endpoints:
        default: http://localhost:3333/graphql
