version: "2"

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - internal
    ports:
      - 6379:6379

volumes:
  pgdata:

networks:
  internal:
    driver: bridge
