version: "2.0"

services:
  app:
    build: .
    restart: always
    environment:
      PORT: 5000
      NODE_ENV: production
      DEPLOYMENT: docker
      NO_SERVE: 1
    networks:
      - internal
    depends_on:
      - postgres
      - redis
    volumes:
      - app_content:/usr/src/app

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal
    ports:
      - 6379:6379

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - internal
    depends_on:
      - app
    volumes:
      - ./certs:/etc/ssl/certs
      - ./configuration/nginx.conf:/etc/nginx/nginx.conf
      - app_content:/usr/src/app

volumes:
  pgdata:
  app_content:

networks:
  internal:
    driver: bridge
