version: 1

database:
  client:
  type:
  database:
  host:
  port:
  username:
  password:
  logger:

queue:
  host:
  port:

mailer:
  host:
  port:
  auth:
    user:
    pass:

  template:
    dir:

auth:
  secret:

graphql:
  schema:
