version: 1

database:
  database: dfmga689la6nn8
  dialect: postgres
  host: ec2-18-232-143-90.compute-1.amazonaws.com
  port: 5432
  username: jnqdganuwskyll
  password: c3d7347eb0c96a523adc157e891d97f4b31bd39e645f1663e8a82e6f014a4394
  logger: true

queue:
  host: ec2-54-157-5-88.compute-1.amazonaws.com
  port: 7429
  password: p0df579f2a4f2eac25d534645f0d61acf76158d26add238d20d060fe166fb1cd3

mailer:
  host: smtp.mailtrap.io
  port: 2525
  auth:
    user: 542484e887f0bc
    pass: 900ed66f62db84

  template:
    dir: src/server/templates

auth:
  secret: HerokuDomusDeployTest

graphql:
  schema: src/server/schema.gql
