version: 1

database:
  database: graphql
  dialect: postgres
  host: postgres
  port: 5432
  username: docker
  password: docker
  logger: true

queue:
  host: redis
  port: 6379

mailer:
  host: smtp.mailtrap.io
  port: 2525
  auth:
    user: 542484e887f0bc
    pass: 900ed66f62db84

  template:
    dir: src/server/templates

auth:
  secret: teste

graphql:
  schema: src/server/schema.graphql
